package CorbaIdl.Camas;


/**
* Camas/CamaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cama.idl
* viernes 16 de noviembre de 2018 01H47' COT
*/

public interface CamaOperations 
{
  boolean insertarCama (int codigoCama, String descripcion, int codigoSala, char estado);
  boolean actualizarCama (int codigoCama, String descripcion, int codigoSala, char estado);
  boolean eliminarCama (int codigoCama);
  String consultarCama (int codigoCama);
  void shutdown ();
} // interface CamaOperations
