package CorbaIdl.Camas;


/**
* Camas/CamaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cama.idl
* viernes 16 de noviembre de 2018 01H47' COT
*/

abstract public class CamaHelper
{
  private static String  _id = "IDL:Camas/Cama:1.0";

  public static void insert (org.omg.CORBA.Any a, CorbaIdl.Camas.Cama that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CorbaIdl.Camas.Cama extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CorbaIdl.Camas.CamaHelper.id (), "Cama");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CorbaIdl.Camas.Cama read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CamaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CorbaIdl.Camas.Cama value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CorbaIdl.Camas.Cama narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaIdl.Camas.Cama)
      return (CorbaIdl.Camas.Cama)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaIdl.Camas._CamaStub stub = new CorbaIdl.Camas._CamaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CorbaIdl.Camas.Cama unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaIdl.Camas.Cama)
      return (CorbaIdl.Camas.Cama)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaIdl.Camas._CamaStub stub = new CorbaIdl.Camas._CamaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
