package CorbaIdl.Camas;


/**
* Camas/Cama.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cama.idl
* viernes 16 de noviembre de 2018 01H47' COT
*/

public interface Cama extends CamaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cama
