package CorbaIdl.Camas;


/**
* Camas/CamaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cama.idl
* viernes 16 de noviembre de 2018 01H47' COT
*/

public abstract class CamaPOA extends org.omg.PortableServer.Servant
 implements CorbaIdl.Camas.CamaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarCama", new java.lang.Integer (0));
    _methods.put ("actualizarCama", new java.lang.Integer (1));
    _methods.put ("eliminarCama", new java.lang.Integer (2));
    _methods.put ("consultarCama", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Camas/Cama/insertarCama
       {
         int codigoCama = in.read_long ();
         String descripcion = in.read_wstring ();
         int codigoSala = in.read_long ();
         char estado = in.read_wchar ();
         boolean $result = false;
         $result = this.insertarCama (codigoCama, descripcion, codigoSala, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Camas/Cama/actualizarCama
       {
         int codigoCama = in.read_long ();
         String descripcion = in.read_wstring ();
         int codigoSala = in.read_long ();
         char estado = in.read_wchar ();
         boolean $result = false;
         $result = this.actualizarCama (codigoCama, descripcion, codigoSala, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Camas/Cama/eliminarCama
       {
         int codigoCama = in.read_long ();
         boolean $result = false;
         $result = this.eliminarCama (codigoCama);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Camas/Cama/consultarCama
       {
         int codigoCama = in.read_long ();
         String $result = null;
         $result = this.consultarCama (codigoCama);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Camas/Cama/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Camas/Cama:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Cama _this() 
  {
    return CamaHelper.narrow(
    super._this_object());
  }

  public Cama _this(org.omg.CORBA.ORB orb) 
  {
    return CamaHelper.narrow(
    super._this_object(orb));
  }


} // class CamaPOA
