package CorbaIdl.Camas;

/**
* Camas/CamaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cama.idl
* viernes 16 de noviembre de 2018 01H47' COT
*/

public final class CamaHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaIdl.Camas.Cama value = null;

  public CamaHolder ()
  {
  }

  public CamaHolder (CorbaIdl.Camas.Cama initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaIdl.Camas.CamaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaIdl.Camas.CamaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaIdl.Camas.CamaHelper.type ();
  }

}
