package CorbaIdl.Hospitales;


/**
* Hospitales/Hospital.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hospital.idl
* jueves 15 de noviembre de 2018 21H59' COT
*/

public interface Hospital extends HospitalOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hospital
