package CorbaIdl.Hospitales;


/**
* Hospitales/HospitalPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hospital.idl
* jueves 15 de noviembre de 2018 21H59' COT
*/

public abstract class HospitalPOA extends org.omg.PortableServer.Servant
 implements CorbaIdl.Hospitales.HospitalOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarHospital", new java.lang.Integer (0));
    _methods.put ("actualizarHospital", new java.lang.Integer (1));
    _methods.put ("eliminarHospital", new java.lang.Integer (2));
    _methods.put ("consultarHospital", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Hospitales/Hospital/insertarHospital
       {
         int codigo = in.read_long ();
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         String telefono = in.read_wstring ();
         String estado = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarHospital (codigo, nombre, direccion, telefono, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Hospitales/Hospital/actualizarHospital
       {
         int codigo = in.read_long ();
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         String telefono = in.read_wstring ();
         String estado = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarHospital (codigo, nombre, direccion, telefono, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Hospitales/Hospital/eliminarHospital
       {
         int codigo = in.read_long ();
         boolean $result = false;
         $result = this.eliminarHospital (codigo);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Hospitales/Hospital/consultarHospital
       {
         int codigo = in.read_long ();
         String $result = null;
         $result = this.consultarHospital (codigo);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Hospitales/Hospital/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Hospitales/Hospital:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Hospital _this() 
  {
    return HospitalHelper.narrow(
    super._this_object());
  }

  public Hospital _this(org.omg.CORBA.ORB orb) 
  {
    return HospitalHelper.narrow(
    super._this_object(orb));
  }


} // class HospitalPOA
