package CorbaIdl.Hospitales;

/**
* Hospitales/HospitalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hospital.idl
* jueves 15 de noviembre de 2018 21H59' COT
*/

public final class HospitalHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaIdl.Hospitales.Hospital value = null;

  public HospitalHolder ()
  {
  }

  public HospitalHolder (CorbaIdl.Hospitales.Hospital initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaIdl.Hospitales.HospitalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaIdl.Hospitales.HospitalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaIdl.Hospitales.HospitalHelper.type ();
  }

}
