package CorbaIdl.Pacientes;


/**
* Pacientes/PacientePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Paciente.idl
* viernes 16 de noviembre de 2018 03H01' COT
*/

public abstract class PacientePOA extends org.omg.PortableServer.Servant
 implements CorbaIdl.Pacientes.PacienteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarPaciente", new java.lang.Integer (0));
    _methods.put ("actualizarPaciente", new java.lang.Integer (1));
    _methods.put ("eliminarPaciente", new java.lang.Integer (2));
    _methods.put ("consultarPaciente", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Pacientes/Paciente/insertarPaciente
       {
         int cedulaPaciente = in.read_long ();
         int codigoCama = in.read_long ();
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         char estado = in.read_wchar ();
         boolean $result = false;
         $result = this.insertarPaciente (cedulaPaciente, codigoCama, nombre, direccion, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Pacientes/Paciente/actualizarPaciente
       {
         int cedulaPaciente = in.read_long ();
         int codigoCama = in.read_long ();
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         char estado = in.read_wchar ();
         boolean $result = false;
         $result = this.actualizarPaciente (cedulaPaciente, codigoCama, nombre, direccion, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Pacientes/Paciente/eliminarPaciente
       {
         int cedulaPaciente = in.read_long ();
         boolean $result = false;
         $result = this.eliminarPaciente (cedulaPaciente);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Pacientes/Paciente/consultarPaciente
       {
         int cedulaPaciente = in.read_long ();
         String $result = null;
         $result = this.consultarPaciente (cedulaPaciente);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Pacientes/Paciente/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Pacientes/Paciente:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Paciente _this() 
  {
    return PacienteHelper.narrow(
    super._this_object());
  }

  public Paciente _this(org.omg.CORBA.ORB orb) 
  {
    return PacienteHelper.narrow(
    super._this_object(orb));
  }


} // class PacientePOA
