package CorbaIdl.Pacientes;

/**
* Pacientes/PacienteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Paciente.idl
* viernes 16 de noviembre de 2018 03H01' COT
*/

public final class PacienteHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaIdl.Pacientes.Paciente value = null;

  public PacienteHolder ()
  {
  }

  public PacienteHolder (CorbaIdl.Pacientes.Paciente initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaIdl.Pacientes.PacienteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaIdl.Pacientes.PacienteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaIdl.Pacientes.PacienteHelper.type ();
  }

}
