package CorbaIdl.Pacientes;


/**
* Pacientes/Paciente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Paciente.idl
* viernes 16 de noviembre de 2018 03H01' COT
*/

public interface Paciente extends PacienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Paciente
