package CorbaIdl.Pacientes;


/**
* Pacientes/PacienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Paciente.idl
* viernes 16 de noviembre de 2018 03H01' COT
*/

public interface PacienteOperations 
{
  boolean insertarPaciente (int cedulaPaciente, int codigoCama, String nombre, String direccion, char estado);
  boolean actualizarPaciente (int cedulaPaciente, int codigoCama, String nombre, String direccion, char estado);
  boolean eliminarPaciente (int cedulaPaciente);
  String consultarPaciente (int cedulaPaciente);
  void shutdown ();
} // interface PacienteOperations
