package CorbaIdl.Medicos;


/**
* Medicos/_MedicoStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Medico.idl
* jueves 15 de noviembre de 2018 21H59' COT
*/

public class _MedicoStub extends org.omg.CORBA.portable.ObjectImpl implements CorbaIdl.Medicos.Medico
{

  public boolean insertarMedico (int cedulaMedico, int codigoHospital, String nombre, String especialidad, char estado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarMedico", true);
                $out.write_long (cedulaMedico);
                $out.write_long (codigoHospital);
                $out.write_wstring (nombre);
                $out.write_wstring (especialidad);
                $out.write_wchar (estado);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarMedico (cedulaMedico, codigoHospital, nombre, especialidad, estado        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarMedico

  public boolean actualizarMedico (int cedulaMedico, int codigoHospital, String nombre, String especialidad, char estado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarMedico", true);
                $out.write_long (cedulaMedico);
                $out.write_long (codigoHospital);
                $out.write_wstring (nombre);
                $out.write_wstring (especialidad);
                $out.write_wchar (estado);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarMedico (cedulaMedico, codigoHospital, nombre, especialidad, estado        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarMedico

  public boolean eliminarMedico (int cedulaMedico)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarMedico", true);
                $out.write_long (cedulaMedico);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarMedico (cedulaMedico        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarMedico

  public String consultarMedico (int cedulaMedico)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarMedico", true);
                $out.write_long (cedulaMedico);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarMedico (cedulaMedico        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarMedico

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Medicos/Medico:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _MedicoStub
