package CorbaIdl.Medicos;


/**
* Medicos/Medico.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Medico.idl
* jueves 15 de noviembre de 2018 21H59' COT
*/

public interface Medico extends MedicoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Medico
