package CorbaIdl.Medicos;


/**
* Medicos/MedicoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Medico.idl
* jueves 15 de noviembre de 2018 21H59' COT
*/

abstract public class MedicoHelper
{
  private static String  _id = "IDL:Medicos/Medico:1.0";

  public static void insert (org.omg.CORBA.Any a, CorbaIdl.Medicos.Medico that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CorbaIdl.Medicos.Medico extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CorbaIdl.Medicos.MedicoHelper.id (), "Medico");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CorbaIdl.Medicos.Medico read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MedicoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CorbaIdl.Medicos.Medico value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CorbaIdl.Medicos.Medico narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaIdl.Medicos.Medico)
      return (CorbaIdl.Medicos.Medico)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaIdl.Medicos._MedicoStub stub = new CorbaIdl.Medicos._MedicoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CorbaIdl.Medicos.Medico unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaIdl.Medicos.Medico)
      return (CorbaIdl.Medicos.Medico)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaIdl.Medicos._MedicoStub stub = new CorbaIdl.Medicos._MedicoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
