package CorbaIdl.Medicos;


/**
* Medicos/MedicoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Medico.idl
* jueves 15 de noviembre de 2018 21H59' COT
*/

public interface MedicoOperations 
{
  boolean insertarMedico (int cedulaMedico, int codigoHospital, String nombre, String especialidad, char estado);
  boolean actualizarMedico (int cedulaMedico, int codigoHospital, String nombre, String especialidad, char estado);
  boolean eliminarMedico (int cedulaMedico);
  String consultarMedico (int cedulaMedico);
  void shutdown ();
} // interface MedicoOperations
