package CorbaIdl.Medicos;


/**
* Medicos/MedicoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Medico.idl
* jueves 15 de noviembre de 2018 21H59' COT
*/

public abstract class MedicoPOA extends org.omg.PortableServer.Servant
 implements CorbaIdl.Medicos.MedicoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarMedico", new java.lang.Integer (0));
    _methods.put ("actualizarMedico", new java.lang.Integer (1));
    _methods.put ("eliminarMedico", new java.lang.Integer (2));
    _methods.put ("consultarMedico", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Medicos/Medico/insertarMedico
       {
         int cedulaMedico = in.read_long ();
         int codigoHospital = in.read_long ();
         String nombre = in.read_wstring ();
         String especialidad = in.read_wstring ();
         char estado = in.read_wchar ();
         boolean $result = false;
         $result = this.insertarMedico (cedulaMedico, codigoHospital, nombre, especialidad, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Medicos/Medico/actualizarMedico
       {
         int cedulaMedico = in.read_long ();
         int codigoHospital = in.read_long ();
         String nombre = in.read_wstring ();
         String especialidad = in.read_wstring ();
         char estado = in.read_wchar ();
         boolean $result = false;
         $result = this.actualizarMedico (cedulaMedico, codigoHospital, nombre, especialidad, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Medicos/Medico/eliminarMedico
       {
         int cedulaMedico = in.read_long ();
         boolean $result = false;
         $result = this.eliminarMedico (cedulaMedico);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Medicos/Medico/consultarMedico
       {
         int cedulaMedico = in.read_long ();
         String $result = null;
         $result = this.consultarMedico (cedulaMedico);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Medicos/Medico/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Medicos/Medico:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Medico _this() 
  {
    return MedicoHelper.narrow(
    super._this_object());
  }

  public Medico _this(org.omg.CORBA.ORB orb) 
  {
    return MedicoHelper.narrow(
    super._this_object(orb));
  }


} // class MedicoPOA
