package CorbaIdl.Medicos;

/**
* Medicos/MedicoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Medico.idl
* jueves 15 de noviembre de 2018 21H59' COT
*/

public final class MedicoHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaIdl.Medicos.Medico value = null;

  public MedicoHolder ()
  {
  }

  public MedicoHolder (CorbaIdl.Medicos.Medico initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaIdl.Medicos.MedicoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaIdl.Medicos.MedicoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaIdl.Medicos.MedicoHelper.type ();
  }

}
