package CorbaIdl.Salas;


/**
* Salas/Sala.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sala.idl
* viernes 16 de noviembre de 2018 00H19' COT
*/

public interface Sala extends SalaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sala
