package CorbaIdl.Salas;

/**
* Salas/SalaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sala.idl
* viernes 16 de noviembre de 2018 00H19' COT
*/

public final class SalaHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaIdl.Salas.Sala value = null;

  public SalaHolder ()
  {
  }

  public SalaHolder (CorbaIdl.Salas.Sala initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaIdl.Salas.SalaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaIdl.Salas.SalaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaIdl.Salas.SalaHelper.type ();
  }

}
