package CorbaIdl.Salas;


/**
* Salas/SalaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Sala.idl
* viernes 16 de noviembre de 2018 00H19' COT
*/

public abstract class SalaPOA extends org.omg.PortableServer.Servant
 implements CorbaIdl.Salas.SalaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarSala", new java.lang.Integer (0));
    _methods.put ("actualizarSala", new java.lang.Integer (1));
    _methods.put ("eliminarSala", new java.lang.Integer (2));
    _methods.put ("consultarSala", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Salas/Sala/insertarSala
       {
         int codigoSala = in.read_long ();
         int codigoHospital = in.read_long ();
         String nombre = in.read_wstring ();
         char estado = in.read_wchar ();
         boolean $result = false;
         $result = this.insertarSala (codigoSala, codigoHospital, nombre, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Salas/Sala/actualizarSala
       {
         int codigoSala = in.read_long ();
         int codigoHospital = in.read_long ();
         String nombre = in.read_wstring ();
         char estado = in.read_wchar ();
         boolean $result = false;
         $result = this.actualizarSala (codigoSala, codigoHospital, nombre, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Salas/Sala/eliminarSala
       {
         int codigoSala = in.read_long ();
         boolean $result = false;
         $result = this.eliminarSala (codigoSala);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Salas/Sala/consultarSala
       {
         int codigoSala = in.read_long ();
         String $result = null;
         $result = this.consultarSala (codigoSala);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Salas/Sala/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Salas/Sala:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Sala _this() 
  {
    return SalaHelper.narrow(
    super._this_object());
  }

  public Sala _this(org.omg.CORBA.ORB orb) 
  {
    return SalaHelper.narrow(
    super._this_object(orb));
  }


} // class SalaPOA
